version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order
    volumes:
      - ./data:/var/lib/postgresql/data
